name: prediction

on:
  schedule:
    - cron: "59 15 * * *"
  workflow_dispatch:

jobs:
  prediction_1:
    runs-on: ubuntu-latest
    outputs:
      php: ${{ steps.php.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - name: Preprocessing
        run: |
          cd src
          composer install
      - name: Run PHP
        id: php
        run: |
          php src/ml.php 1
  prediction_2:
    runs-on: ubuntu-latest
    outputs:
      php: ${{ steps.php.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - name: Preprocessing
        run: |
          cd src
          composer install
      - name: Run PHP
        id: php
        run: |
          php src/ml.php 2
  prediction_3:
    runs-on: ubuntu-latest
    outputs:
      php: ${{ steps.php.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - name: Preprocessing
        run: |
          cd src
          composer install
      - name: Run PHP
        id: php
        run: |
          php src/ml.php 3
  prediction_4:
    runs-on: ubuntu-latest
    outputs:
      php: ${{ steps.php.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - name: Preprocessing
        run: |
          cd src
          composer install
      - name: Run PHP
        id: php
        run: |
          php src/ml.php 4
  prediction_5:
    runs-on: ubuntu-latest
    outputs:
      php: ${{ steps.php.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - name: Preprocessing
        run: |
          cd src
          composer install
      - name: Run PHP
        id: php
        run: |
          php src/ml.php 5
  prediction_6:
    runs-on: ubuntu-latest
    outputs:
      php: ${{ steps.php.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - name: Preprocessing
        run: |
          cd src
          composer install
      - name: Run PHP
        id: php
        run: |
          php src/ml.php 6
  prediction_7:
    runs-on: ubuntu-latest
    outputs:
      php: ${{ steps.php.outputs.result }}
    steps:
      - uses: actions/checkout@v3
      - name: Preprocessing
        run: |
          cd src
          composer install
      - name: Run PHP
        id: php
        run: |
          php src/ml.php 7

  result:
    runs-on: ubuntu-latest
    needs: [prediction_5, prediction_6, prediction_7]
    steps:
      - name: output
        run: |
          cat << 'EOF' > data/log/`date +%Y%m%d`.csv
          ${{needs.prediction_1.outputs.php}}
          ${{needs.prediction_2.outputs.php}}
          ${{needs.prediction_3.outputs.php}}
          ${{needs.prediction_4.outputs.php}}
          ${{needs.prediction_5.outputs.php}}
          ${{needs.prediction_6.outputs.php}}
          ${{needs.prediction_7.outputs.php}}
          EOF
          cat data/log/`date +%Y%m%d`.csv
          ls -la data/
          ls -la data/log/
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      - name: git push
        run: |
          git add data/log/`date +%Y%m%d`.csv
          git commit -m "add `date +%Y%m%d`.csv"
          git push origin HEAD
